# Use Apache NuttX’s Docker image as the base image. Refer to its Dockerfile here: https://github.com/apache/nuttx/blob/master/tools/ci/docker/linux/Dockerfile
FROM ghcr.io/apache/nuttx/apache-nuttx-ci-linux

# Install tools specific for openvela.
RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y -qq \
    build-essential \
    cmake \
    git \
    libgl1-mesa-glx \
    libncurses5-dev \
    libncursesw5-dev \
    libssl-dev \
    python3 \
    python3-pip \
    curl \
    jq \
    git-lfs \
    dosfstools \
    mtools \
    libc++abi1 \
    srecord
RUN git lfs install
RUN git lfs --version
RUN pip3 install matplotlib==3.6.2
RUN pip3 install html-table
RUN rm -rf /var/lib/apt/lists/*

# Set the command to be executed when the container starts.
CMD ["/bin/bash"]
